name: CUPS for Zebra
version: "1.7.4"
slug: cups
description: A CUPS print server to expose and filter Zebra print jobs
arch:
  - amd64
  - aarch64
usb: true
init: false
homeassistant_api: true
host_network: true
ports:
  631/tcp: 631
  631/udp: 631
ports_description:
  631/tcp: For other devices on the local network to print to this server
  631/udp: For other devices on the local network to print to this server
map:
  - addon_config:rw
